export const jrxRolesAndDescription: string[][] = [
    ['JRX Super Admin', 'JRX Dashboard owner, has access to all Apps - Is a clixlogix-samplecode Employee and has access to the entire dashboard, can add other clixlogix-samplecode Super Admins upto 3 JRX super admins max can be added, clixlogix-samplecode super admins are not visible on the team tables of external developers dashboard team access control. Has exclusive access prerogative of only clixlogix-samplecode super admin such as User access, Blitz events config, etc.'],
    ['JRX Manager', 'Has access to all Apps - Is a clixlogix-samplecode Employee and has access to the entire dashboard, can add other clixlogix-samplecode Managers, clixlogix-samplecode Managers are not visible on the team tables of external developers dashboard team access control. Has exclusive access prerogative of only clixlogix-samplecode employees similar to clixlogix-samplecode super admin except Users data.Has access to all Apps - Is a clixlogix-samplecode Employee and has access to the entire dashboard, can add other clixlogix-samplecode Managers, clixlogix-samplecode Managers are not visible on the team tables of external developers dashboard team access control. Has exclusive access prerogative of only clixlogix-samplecode employees similar to clixlogix-samplecode super admin except external billing and contract information. To the users below this segment Users, S2S config, App params, Release management sections wont appear.'],
    ['JRX Team member', 'Has access to all Apps - Is a clixlogix-samplecode Employee and has access to the entire dashboard similar to JRX manager except User data and CMS user control, JRX team member are not visible on the team tables of external developers dashboard team access control.'],
    ['JRX view only access', 'Has view only access to all Apps - Is a clixlogix-samplecode Employee and has view only access to the entire dashboard similar to JRX manager except User data and CMS user control, JRX team member are not visible on the team tables of external developers dashboard team access control.'],
];

export const rolesAndDescription: string[][] = [
    ['Owner/Admin', 'Is the company account owner - who created this App account and has all permissions pertaining to the company, has exclusive access in the company to billing & contract, only one Admin per company is allowed.'],
    ['Manager', 'Has full dashboard access and all account permissions similar to that of Admin pertaining to the company, except billing/contract information.'],
    ['Team Member', 'Has full dashboard access and all account permissions similar to that of Manager pertaining to the company except CMS user control.'],
    ['View Only Access', 'Has dashboard view only access and view of all the sections and edit access to the test environment.'],
];